ServerName localhost

LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so
LoadModule rewrite_module modules/mod_rewrite.so

Listen 80

<VirtualHost *:80>

    ProxyRequests Off

    ProxyPass "/" "http://app:8080/"
    ProxyPassReverse "/" "http://app:8080/"

    # 👇 If Tomcat is DOWN
    ErrorDocument 503 /maintenance.html
    ProxyErrorOverride On

</VirtualHost>
